import { appleAuth } from '@invertase/react-native-apple-authentication';

import { type ProviderNames } from '@/core/firebase/types';

export interface AppleIdentity {
  identityToken: string | null;
  /** Raw nonce generated by the library; Apple receives its SHA-256 hash. */
  nonce: string;
  /** Short-lived code used to revoke the Apple token when the account is deleted (D17). */
  authorizationCode: string | null;
  /** Apple shares the name only on the first authorisation for this app. */
  names: ProviderNames;
}

/** Shows the Sign in with Apple sheet (iOS). Rejects with code "1001" when cancelled. */
export const requestAppleIdentity = async (): Promise<AppleIdentity> => {
  const response = await appleAuth.performRequest({
    requestedOperation: appleAuth.Operation.LOGIN,
    requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
  });
  return {
    identityToken: response.identityToken,
    nonce: response.nonce,
    authorizationCode: response.authorizationCode,
    names: {
      firstName: response.fullName?.givenName ?? undefined,
      lastName: response.fullName?.familyName ?? undefined,
    },
  };
};

export const isAppleCancellation = (error: unknown) =>
  (error as { code?: unknown })?.code === appleAuth.Error.CANCELED;
