default_platform(:ios)

before_all do
  setup_ci(
    force: true # This will make sure the environment is really clean
  ) # Creates a temporary keychain and sets it as the default
end

platform :ios do
  desc "Distribute latest version pointing to dev environment"
  lane :build_and_distribute_dev_app do
        # Match certificates and provisioning profiles
        match(
            type: "development",
            app_identifier: "com.qdmobile.dev",
            readonly: true
        )

        # Sync certificates and provisioning profiles
        sync_code_signing(
          type: "development",
          readonly: true
        )

        # Increment the build number to ensure uniqueness
#         increment_build_number(xcodeproj: "QDMobile.xcodeproj")

        # Build your app
        build_app(
          scheme: "QDMobileDev",
          workspace: "QDMobile.xcworkspace",
          export_method: "development",
          clean: true,
          xcargs: "-allowProvisioningUpdates"
        )

        firebase_app_distribution(
          app: "1:476492543939:ios:2626c5976a5643d0a66f76",
        )

        # Commit the version increment
#         git_commit(
#           path: "QDMobile.xcodeproj/project.pbxproj", # Specify the path to the file(s) that were modified
#           message: "Increment build number after distribution"
#         )

        # Optional: Push the commit to your git remote
#         push_to_git_remote(
#           remote: "origin", # Specify your git remote
#           local_branch: "main", # Specify the local branch to push
#           remote_branch: "main", # Specify the remote branch to push to
#           force: false # Set to true to force push
#         )
  end
end
