# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end
#
#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
#
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end
#
#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end

  desc "Deploy to firebase development app distribution"
  lane :distribute_dev_app do
    firebase_app_distribution(
        app: "1:476492543939:android:78fda527c441d302a66f76",
        android_artifact_path: "app/build/outputs/apk/development/release/app-development-release.apk"
    )
  end

  desc "Deploy to firebase production app distribution"
  lane :distribute_prod_app do
    firebase_app_distribution(
        app: "1:993625301555:android:768b283d3ddca74a787946",
        android_artifact_path: "app/build/outputs/apk/production/release/app-production-release.apk"
    )
  end

  lane :deploy_to_play_store do
    supply(
      track: 'alpha', # Can be: production, beta, alpha, or internal
      package_name: 'com.qdmobile',
      aab: 'app/build/outputs/bundle/productionRelease/app-production-release.aab', # Or use aab: for Android App Bundles
      json_key: 'google-play-key.json',
      skip_upload_metadata: true, # Set to false if you want to upload metadata
      skip_upload_images: true, # Set to false if you want to upload images
      skip_upload_screenshots: true # Set to false if you want to upload screenshots
    )
  end
end
